title: Site pessoal de Antonio Lazaro (Popete)
description: Site pessoal de Antonio Lazaro (Popete)
author: Antonio Lazaro (Popete)
github: https://github.com/antoniolazaro
about: Software Architecht @ Indra Company. Site pessoal Antonio Lazaro (Popete). Site com objetivo de compartilhar experiências e percepções pessoais durante minha jornada...
disqus_shortname: antoniolazaro-github-io
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.png

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "http://twitter.com/antonio_lazaro"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/antonio-lazaro-carvalho-borges-a78a1514/"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/antoniolazaro"
    - icon: fa-gitlab
      link: "https://gitlab.com/antoniolazaro"
    - icon: fa-skype
      link: "@alazaro.carvalho"
    - icon: fa-slideshare
      link: "https://www.slideshare.net/antoniolazarobr"

share:
  twitter_username: antonio_lazaro
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projetos
      url: /projects/
    - text: Palestras e Eventos
      url: /talks/
    - text: Formação
      url: /studies/
    - text: Carreira
      url: /carrer/   
    - text: XML Feed
      url: /feed.xml

url: "https://antoniolazaro.dev"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
