# Site settings
title: Antonio Lazaro Carvalho Borges
description: 'Java Software Developer, interisting in learn about other topics as: Data Science, Machine Learning (and IA stuffs), Mobile development, NoSQL and other stuffs.'
url: 'https://antoniolazaro.github.io/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Antonio Lazaro Carvalho Borges'
  email: antonio.lazaro@gmail.com
  twitter_username: antonio_lazaro
  #facebook_username: joshgerdes
  github_username:  antoniolazaro
  linkedin_username:  antonio-lazaro-carvalho-borges-a78a1514

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
